rancher:
  hostname: rancher.idp.example.com
  replicas: 3
  ingress:
    tls:
      source: letsEncrypt
    extraAnnotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  letsEncrypt:
    email: platform@example.com
    environment: production
  bootstrapPassword: ""  # Set via secret
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi
